global_costmap:  
  global_frame: /map
  robot_base_frame: base_footprint
  update_frequency: 4.0
  publish_frequency: 1.0
  static_map: true

  plugins:   
   - {name: static_map,       type: "costmap_2d::StaticLayer"}
   - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
   - {name: inflater,         type: "costmap_2d::InflationLayer"}
